User-Movie Recommendation Model

In [2]:
import pandas as pd
import numpy as np

In [22]:
df = pd.read_csv("C:\\dataset\\Recommend.csv")
# adding Column names to the data frame
df.columns= ['user_id','movie_id','ratings','timestamp']

In [23]:
df

user_id  movie_id  ratings  timestamp
0          186       302        3  891717742
1           22       377        1  878887116
2          244        51        2  880606923
3          166       346        1  886397596
4          298       474        4  884182806
...        ...       ...      ...        ...
99994      880       476        3  880175444
99995      716       204        5  879795543
99996      276      1090        1  874795795
99997       13       225        2  882399156
99998       12       203        3  879959583

[99999 rows x 4 columns]

We must know the number of users and the number of movies since we are creating a user movie recommendation model

In [41]:
from sklearn.model_selection import train_test_split
n_users = df.user_id.unique().shape[0]
n_movies = df.movie_id.unique().shape[0]
train_data,test_data = train_test_split(df,test_size = 0.25)

1682

In [42]:
n_users,n_movies

(943, 1682)

In [33]:
# first create a zero matrix as  for both users and movies
train_data_matrix = np.zeros((n_users,n_movies))
# populate the train and test mehtods with ratings
for line in train_data.itertuples():
    train_data_matrix[line[1]-1,line[2]-1] =line[3]
train_data_matrix

array([[5., 3., 4., ..., 0., 0., 0.],
       [4., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [5., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.]])

In [35]:
# Now that we have some rating for the training set, lets do the same for the testing set
test_data_matrix = np.zeros((n_users,n_movies))
# populate the train and test mehtods with ratings
for line in test_data.itertuples():
    test_data_matrix[line[1]-1,line[2]-1] =line[3]
test_data_matrix

array([[0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 5., 0., ..., 0., 0., 0.]])

Now we want to create cosine Similarities for the user_movie
Cosine similarities is a measure of two non zero vector

In [40]:
from sklearn.metrics import pairwise_distances
user_similarity = pairwise_distances(train_data_matrix, metric = 'cosine')
movie_similarity = pairwise_distances(train_data_matrix.T,metric = 'cosine')
mean_user_rating = train_data_matrix.mean(axis=1)[:,np.newaxis]
ratings_diff =(train_data_matrix - mean_user_rating)
user_pred = mean_user_rating + user_similarity.dot(ratings_diff)/np.array([np.abs(user_similarity).
                                                                                sum(axis=1)]).T
user_pred

array([[0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.]])